// Portfolio data - Featured projects have dedicated pages, others are external links only

export interface FeaturedProject {
  id: string
  slug: string
  title: string
  client: string
  category: "website" | "ecommerce" | "app" | "custom"
  categoryLabel: string
  description: string
  shortDescription: string
  image: string
  results: { label: string; value: string }[]
  technologies: string[]
  year: string
  testimonial?: {
    quote: string
    author: string
    role: string
  }
  challenge: string
  solution: string
  liveUrl?: string
}

export interface SimpleProject {
  id: string
  title: string
  client: string
  category: "website" | "ecommerce" | "app" | "custom"
  categoryLabel: string
  image: string
  liveUrl: string
  year: string
  shortDescription?: string
  order?: number // For custom sorting in grid
}

export const featuredProjects: FeaturedProject[] = [
  {
    id: "1",
    slug: "un-event",
    title: "UN:EVENT – Platformă pentru locații, servicii și evenimente",
    client: "PIXEL FACTORY SRL",
    category: "custom",
    categoryLabel: "Platformă digitală",
    description:
      "Platformă digitală care conectează locații, furnizori și organizatori de evenimente într-un singur ecosistem. Filtrare inteligentă, listări validate, vizibilitate reală și alte sisteme integrate.",
    shortDescription: "Platformă digitală pentru simplificarea găsirii de locații, servicii și evenimente.",
    image: "/projects/UnEvent.webp",
    results: [
      { label: "Listări în prima lună", value: "61+" },
      { label: "Viteză încărcare", value: "0.4s" },
      { label: "Core Web Vitals - SEO", value: "100%" },
    ],
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "Railway", "Vercel", "Resend", "Sentry", "Payload CMS", "PostgreSQL", "Map Integration", "Scalable marketplace logic"],
    year: "2025",
    testimonial: {
      quote:
        "UN:EVENT este un produs propriu aflat în dezvoltare activă. Recenziile provin de la parteneri și utilizatori care folosesc deja platforma în primele etape.",
      author: "Ernest Slach",
      role: "Co-Fonator, UN:EVENT & Website Factory",
    },
    challenge:
      "Organizatorii de evenimente pierd timp căutând locații și furnizori pe multiple platforme, iar furnizorii nu au un canal clar și eficient de vizibilitate online.",
    solution:
      "Am construit UN:EVENT — o platformă digitală care centralizează locații, servicii și evenimente, cu filtre inteligente, listări validate și o experiență gândită pentru decizii rapide și vizibilitate reală.",
    liveUrl: "https://unevent.ro",
  },
  {
    id: "2",
    slug: "blue-phoenix",
    title: "Blue Phoenix – Stil de viață indonezian în România",
    client: "Blue Phoenix Rising Thriving Blooming SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    description:
      "Un magazin online care importă și pune în valoare produse naturale, ceaiuri, cafea de specialitate și suplimente tradiționale din Java, Indonezia — orientat spre consumatori interesați de well-being și alimentație sănătoasă. Unul dintre cei mai vechi parteneri ai Website Factory - Mentenanță din Martie 2023.",
    shortDescription: "Magazin online cu produse naturale din Indonezia. Optimizat pentru conversii și fidelizare.",
    image: "/projects/blue-phoenix.webp",
    results: [
      { label: "Conversii", value: "+120%" },
      { label: "Creștere % în 2 ani", value: "2329%" },
      { label: "Rată abandon", value: "-70%" },
    ],
    technologies: ["Wordpress", "WooCommerce", "MySQL", "Netopia Payments", "Sameday Courier", "Easybox", "SmartBill", "Klaviyo", "Meta Pixel", "Google Ads"],
    year: "2023",
    challenge: "Brandul avea nevoie de o prezență online premium care să vorbească despre originea produselor, valorile culturale și beneficiile naturale — combinând narativul cu un magazin ușor de folosit.",
    solution:
      "Am modernizat prezența online a brandului printr-un design curat, adaptat identității vizuale Blue Phoenix, cu accent pe claritate, coerență și experiență de navigare. Platforma este optimizată pentru viteză de încărcare și utilizare fluentă pe toate dispozitivele, iar structura paginilor este gândită pentru a susține conversia — de la descoperirea produselor până la achiziție. Arhitectura permite extinderea ulterioară a funcționalităților, fără a compromite performanța sau simplitatea experienței.",
    liveUrl: "https://blue-phoenix.ro/",
  },
  {
    id: "3",
    slug: "merpano",
    title: "Merpano - Website de prezentare companie",
    client: "Merpano SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    description:
      "Merpano este o companie importantă din industria agricolă din Vestul României, activă în furnizarea de echipamente, soluții și consultanță pentru fermieri și parteneri din domeniu. Website-ul servește ca unul dintre punctele principale de contact digital: prezentare corporate, portofoliu produse, servicii, echipă și valori.",
    shortDescription: "Website de prezentare pentru o companie importantă din industria agricolă.",
    image: "/projects/merpano.webp",
    results: [
      { label: "Core Web Vitals - SEO ", value: "100%" },
      { label: "Timp mediu petrecut pe site", value: "2:04 min" },
      { label: "Retenție", value: "68%" },
    ],
    technologies: ["Wordpress", "Elementor", "SEO"],
    year: "2024",
  
    challenge:
      "Website-ul existent nu reflecta pe deplin nivelul și profesionalismul companiei: structură depășită, vizual neconectat la brand și UX neoptimizat. Era nevoie de o prezență digitală modernă, coerentă și orientată spre încredere, care să pună în valoare portofoliul larg de produse și expertiza echipei.",
    solution:
      "Am reconceput site-ul Merpano din temelii cu un focus puternic pe modernizare, profesionalism și adaptare vizuală la poziționarea companiei. Am construit un design curat și coerent, ferit de elemente învechite, astfel încât fiecare secțiune — de la servicii și produse până la echipă — să fie ușor de parcurs, intuitivă și credibilă vizual. Structura paginilor și elementele interactive sunt gândite pentru a susține claritatea mesajului și încrederea vizitatorului, în timp ce viteza de încărcare, navigarea și experiența pe mobil asigură o interacțiune eficientă pentru toți utilizatorii. Implementarea pe WordPress cu Elementor personalizat permite gestionarea facilă a conținutului și scalabilitate pe termen lung.",
    liveUrl: "https://merpano.ro/",
  },
  
]


// Manual array of all projects - edit titles, descriptions, URLs, and order here
export const simpleProjects: SimpleProject[] = [
  // Website de prezentare
    {
    id: "s1",
    title: "artimm.digital",
    client: "Artimm Digital SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-artimm-digital.webp",
    liveUrl: "https://artimm.digital/",
    year: "2025",
    shortDescription: "Website de prezentare companie de consultanță digitală, Web design, Web development, SEO",
    order: 1,
  },
  {
    id: "s45",
    title: "Bradluc - Mentenanță Piscine",
    client: "Bradluc M & D SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-bradluc_curatenie.webp",
    liveUrl: "https://piscinetimis.ro/",
    year: "2024",
    shortDescription: "Website de prezentare - Servicii de curățenie și mentenanță piscine, Web design, Web development",
    order: 45,
  },
  {
    id: "s2",
    title: "Thermo Solar Energy",
    client: "Thermo Solar SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/proiect-website-prezentare-thermo-solar-energy.webp",
    liveUrl: "http://thermosolarenergy.ro/",
    year: "2023",
    shortDescription: "Website de prezentare compamnie vanzare de panouri fotovoltaice, Web Design, Mentenanță, Găzduire domeniu, SEO",
    order: 64
  },
  {
    id: "s3",
    title: "Revelio Medical Global",
    client: "Relive Care SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-Revelio.webp",
    liveUrl: "https://reveliomedical.com/",
    year: "2024",
    shortDescription: "Website de prezentare și achiziție abonamente medicale și descărcare aplicație mobilă, Web design, Web development, Mentenanță, domeniu, SEO",
    order: 20,
  },
  {
    id: "s4",
    title: "NN News Media",
    client: "Internațional",
    category: "website",
    categoryLabel: "Website Știri",
    image: "/projects/website-stiri-blog-NN News Media.webp",
    liveUrl: "https://nnnewsmedia.com/",
    year: "2024",
    shortDescription: "Website de știri - Nigeria, Web Design, Design Grafic, Mentenanță, Găzduire domeniu, SEO",
    order: 43,
  },
  {
    id: "s5",
    title: "Hobby Art Afterschool",
    client: "Hobby Art SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/proiect-website-prezentare-afterschool-dumbravita-hobby-art.webp",
    liveUrl: "https://afterschool-dumbravita.ro/",
    year: "2023",
    shortDescription: "Website de prezentare afterschool, Web Design, Mentenanță, Găzduire domeniu, SEO",
    order: 50,
  },
  {
    id: "s6",
    title: "Proval",
    client: "Proval Just SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-Proval.webp",
    liveUrl: "https://proval.ro/",
    year: "2024",
    shortDescription: "Website de prezentare evaluator + formular de evaluare rapida cu plata online, Web design, Web Development, SEO",
    order: 6,
  },
  {
    id: "s7",
    title: "Luxury Cleaning",
    client: "PFA - Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-Luxury Cleaning.webp",
    liveUrl: "http://luxurycleaning.ro/",
    year: "2024",
    shortDescription: "Website de prezentare firmă de curățenie, Web Design, SEO",
    order: 61,
  },
  {
    id: "s8",
    title: "DezzignIst",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-dezzign.webp",
    liveUrl: "https://dezzign.ist/",
    year: "2024",
    shortDescription: "Pagină de prezentare - Designer de interior, Web design, Web development, SEO",
    order: 67,
  },
  {
    id: "s11",
    title: "TheRadar",
    client: "PFA - Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-TheRadar.webp",
    liveUrl: "https://theradar.info/",
    year: "2025",
    shortDescription: "Website de prezentare - Change agent, Web design, Web development, SEO, Mentenanta",
    order: 63,
  },
  {
    id: "s12",
    title: "Youplus Agency",
    client: "YouPlus Agency SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-Youplus.webp",
    liveUrl: "https://youplusagency.ro/",
    year: "2025",
    shortDescription: "Website de prezentare și achiziții cursuri - Agenție de marketing, Web design, Web development, Achiziție în rate cursuri, Design Grafic, SEO",
    order: 9,
  },
  {
    id: "s13",
    title: "ATP Apitherapie Austria",
    client: "PFA - Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-ATP.webp",
    liveUrl: "https://atp-apitherapie.com/",
    year: "2023",
    shortDescription: "Design landing page, Găzduire domeniu, SEO",
    order: 67,
  },
  {
    id: "s15",
    title: "Best Tim Travel",
    client: "Best Tim Travel SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-Best Tim Travel.webp",
    liveUrl: "https://timtravel.ro/",
    year: "2025",
    shortDescription: "Website de prezentare - Agenție de turism, Web design, Web development, Design Grafic, SEO",
    order: 15,
  },
  {
    id: "s18",
    title: "eDrones",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-e-Drones.webp",
    liveUrl: "https://edrones.ro/",
    year: "2024",
    shortDescription: "Website de preszentare - Drone agricole, Web design, Web Development, SEO",
    order: 13,
  },
  {
    id: "s20",
    title: "Maravo Clinic",
    client: "Maravo SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-Maravo.webp",
    liveUrl: "https://maravoclinic.ro/",
    year: "2025",
    shortDescription: "Website de prezentare clinică de înfrumusețare, Web design, Graphic design, Consultanta, Web development, Mentenanță, domeniu, SEO",
    order: 3,
  },
  {
    id: "s21",
    title: "PowerJet Wash",
    client: "NAGY Evolution Construct SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-NAGY EVOLUTION CONSTRUCT.webp",
    liveUrl: "https://powerjetwash.ro/",
    year: "2023",
    shortDescription: "Website de prezentare - Servicii curățenie pavaje, Web design, Web development, Design Grafic",
    order: 21,
  },
  {
    id: "s23",
    title: "Horvel Cleaning Services",
    client: "Horvel Cleaning Services SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-curatenie-Horvel.webp",
    liveUrl: "https://horvel.ro/",
    year: "2024",
    shortDescription: "Website de prezentare - Firmă de curățenie, Web design, Web development, Formular complex de rezervări, Design Grafic, SEO",
    order: 23,
  },
  {
    id: "s24",
    title: "RD Automatim",
    client: "R & D Automatim SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-rdautomatim.webp",
    liveUrl: "https://rdautomatim.com/",
    year: "2025",
    shortDescription: "Website de prezentare - Automatizări industriale, Web design, Web development, SEO",
    order: 24,
  },
  {
    id: "s25",
    title: "Radiotron Tehnologies",
    client: "Radiotron Tehnologies SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-radiotron.webp",
    liveUrl: "https://radiotron.ro/",
    year: "2025",
    shortDescription: "Website de prezentare - Medicină nucleară, Web design, Web development, SEO",
    order: 25,
  },
  {
    id: "s26",
    title: "OK Auto",
    client: "OK Auto SRL",
    category: "website",
    categoryLabel: "Website auto",
    image: "/projects/website-auto-okauto.webp",
    liveUrl: "https://okautotm.ro/",
    year: "2025",
    shortDescription: "Website de prezentare - Website de prezetare și vânzare auto, Web design, Web Development, SEO, Mentenanță",
    order: 26,
  },
  {
    id: "s27",
    title: "Therapy Energy",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-terapie-energetica.webp",
    liveUrl: "https://terapia-energetica.ro/",
    year: "2024",
    shortDescription: "Website prezentare - Terapie Energetică, Web design, Web development, Design Grafic",
    order: 27,
  },
  {
    id: "s28",
    title: "Restaurant Evoratest",
    client: "Evoratest SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-Evoratest.webp",
    liveUrl: "https://evoratest.ro/",
    year: "2024",
    shortDescription: "Website de prezentare restaurant, Pagină meniu, QR, Web design, Web development, Design Grafic",
    order: 28,
  },
  {
    id: "s29",
    title: "Pâinea pe Ape",
    client: " Asociatia umanitara ,,Painea pe ape “",
    category: "website",
    categoryLabel: "Website asociație",
    image: "/projects/website-asociatie-donatii-Painea pe ape.webp",
    liveUrl: "https://paineapeape.ro",
    year: "2024",
    shortDescription: "Website ONG, Sitem donație, Web design, Web development, Design Grafic",
    order: 29,
  },
  {
    id: "s30",
    title: "BimTim Design",
    client: "Bimtim Design SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-bimtim.webp",
    liveUrl: "https://bimtim.com/",
    year: "2025",
    shortDescription: "Website de prezentare - Proiectare digitală clădiri, Web design, Web development, Portofoliu, Design Grafic, SEO",
    order: 14,
  },
  {
    id: "s31",
    title: "AC Green Power Consulting",
    client: "AC Green Power Consulting SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-AC green.webp",
    liveUrl: "https://ac-green-power.eu/",
    year: "2025",
    shortDescription: "Website de prezentare consultanță și proiectare sisteme green power, Web design, Web development, Design grafic, SEO",
    order: 31,
  },
  {
    id: "s32",
    title: "Mobile Spa",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-mobileSpa.webp",
    liveUrl: "https://mobilespa.ro/",
    year: "2025",
    shortDescription: "Pagină de prezentare - Închirierea ciubăr mobil, Web design, Web development, SEO, Design Logo și Branding",
    order: 32,
  },
  {
    id: "s34",
    title: "Avocat Jurjut-Mart",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-timisoara-avocat-Jurjut.webp",
    liveUrl: "https://jurjut-mart.ro/",
    year: "2023",
    shortDescription: "Website de prezentare avocați, Web design, Mentenanță, Găzduire domeniu, Design Logo, SEO",
    order: 15,
  },
  {
    id: "s35",
    title: "Cika România",
    client: "Cika SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-Cika.webp",
    liveUrl: "https://www.cika-romania.ro/",
    year: "2025",
    shortDescription: "Website de preszentare - Companie produse alimentare pentru industria Horeca, Web design, Web Development, SEO",
    order: 35,
  },
  {
    id: "s38",
    title: "Vici Evolution",
    client: "Vici Evolution SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-vici-evolution.webp",
    liveUrl: "https://vicievolution.ro/",
    year: "2024",
    shortDescription: "Website de prezentare companie de medicina nucleara, Web design, Web development, SEO",
    order: 38,
  },
  {
    id: "s39",
    title: "ONG Ame de Vie",
    client: "Asociația Ame de Vie",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-ong-ame-de-vie.webp",
    liveUrl: "https://amedevie.ro/",
    year: "2025",
    shortDescription: "Website de prezentare asociație ONG, Web design, Web development, SEO, Găzduire domeniu",
    order: 39,
  },
  {
    id: "s40",
    title: "Move Auto",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website auto",
    image: "/projects/website-de-prezentare-move-auto.webp",
    liveUrl: "https://moveauto.ro/",
    year: "2025",
    shortDescription: "Website de prezentare, Web Design, Web development, Design Logo, Găzduire domeniu, SEO",
    order: 40,
  },
  {
    id: "s41",
    title: "Lami Ing Eur",
    client: "Lami Ing Eur SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-lami-ing.webp",
    liveUrl: "https://lami-ingeur.ro/",
    year: "2025",
    shortDescription: "Website de prezentare companie de automatizari industriale, Web design, Web development, SEO",
    order: 41,
  },
  {
    id: "s42",
    title: "Înființare SRL",
    client: "Prime Smart Innovations SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-infiintare-srl.webp",
    liveUrl: "https://infiintaresrl-nou.ro/",
    year: "2025",
    shortDescription: "Website de prezentare, Web design, Web development, Design Logo,",
    order: 42,
  },
  {
    id: "s43",
    title: "Geonordica",
    client: "Geonordica SRL",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-geonordica.webp",
    liveUrl: "https://www.geonordica.ro/",
    year: "2025",
    shortDescription: "Website de prezentare firma topografica Iași, Web design, Web development, Mentenanță, Găzduire, SEO",
    order: 4,
  },
  {
    id: "s44",
    title: "Avocat Hinda",
    client: "Confidențial",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-avocat-hinda.webp",
    liveUrl: "https://avocathinda.ro/",
    year: "2025",
    shortDescription: "Website de prezentare avocat, Web design, Mentenanță, Găzduire domeniu, Design Logo, SEO",
    order: 44,
  },
  {
    id: "s46",
    title: "Arpeggio Clinic",
    client: "Arpeggio Clinic AB",
    category: "website",
    categoryLabel: "Website de prezentare",
    image: "/projects/website-de-prezentare-arpeggio-clinic.webp",
    liveUrl: "#",
    year: "2025",
    shortDescription: "Website de prezentare clinică terapeutică suedeză, Web Design, Web Development, Graphic design, SEO",
    order: 46,
  },
  // Magazine online
  {
    id: "s47",
    title: "DKP Solutions",
    client: "DPK Solutions SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-DPK.webp",
    liveUrl: "https://dkpsolutions.ro/",
    year: "2024",
    shortDescription: "Magazin online si inchiriere scule Timișoara, Web design, Web development, Design grafic, Mentenanță, SEO",
    order: 47,
  },
  {
    id: "s48",
    title: "La Pinocchio",
    client: "Pizza Oscar DM SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-Pinnochio.webp",
    liveUrl: "https://clatite-pinochio.ro/",
    year: "2023",
    shortDescription: "Magazin online - restaurant comenzi la domiciliu, Mentenanță, Marketing Digital, Web Design, Web Development, Design grafic, SEO",
    order: 16,
  },
  {
    id: "s49",
    title: "Scar Influence",
    client: "Confidențial",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-Scar.webp",
    liveUrl: "Aplicație online de vânzare haine adolescenți, Scanare QR unic Web design, Web Development, Next.js - React, Găzduire, SEO, Mentenanta",
    year: "2025",
    shortDescription: "Aplicație online de vânzare haine adolescenți, Scanare QR unic Web design, Web Development, Next.js - React, Găzduire, SEO, Mentenanta",
    order: 5,
  },
  {
    id: "s51",
    title: "Rigolabeton.ro",
    client: "Confidențial",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-Rigolabeton.webp",
    liveUrl: "https://rigolabeton.ro/",
    year: "2024",
    shortDescription: "Magazin online - Firmă de construcții, Web design, Mentenanță, Design Logo, SEO",
    order: 51,
  },
  {
    id: "s52",
    title: "Frentzy Supermarket",
    client: "Frentzy Fresh Carn SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-Frentzy.webp",
    liveUrl: "https://frentzy.ro/",
    year: "2023",
    shortDescription: "Supermarket Online, Web design, Web development, Administrare, Design grafic, Marketing digital, SEO",
    order: 52,
  },
  {
    id: "s53",
    title: "Bradluc - Magazin online",
    client: "Bradluc M & D SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-bradluc.webp",
    liveUrl: "https://bradluc.ro/",
    year: "2024",
    shortDescription: "Magazin online produse piscină, Web design, Web development",
    order: 53,
  },
  {
    id: "s54",
    title: "Ornella Fusion Gallery",
    client: "Ornella Fusion Gallery SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-Ornella Gallery.webp",
    liveUrl: "https://ornellafusiongallery.com/",
    year: "2024",
    shortDescription: "Magazin Online - Galerie de Artă, Web design, Web development, SEO",
    order: 54,
  },
  {
    id: "s55",
    title: "Ornella Design",
    client: "Ornella Design SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-Ornella.webp",
    liveUrl: "https://ornelladesign.ro/",
    year: "2023",
    shortDescription: "Magazin Online - Print Shop, Web design, Web Development, SEO",
    order: 55,
  },
  {
    id: "s61",
    title: "Restaurant Gloria",
    client: "URBAN KITCHEN SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-timisoara-Gloria.webp",
    liveUrl: "https://restaurant-gloria.ro/",
    year: "2024",
    shortDescription: "Magazin online - restaurant comenzi la domiciliu, Mentenanță, Marketing Digital, Web Design, Web Development, Design grafic, SEO",
    order: 7,
  },
  {
    id: "s62",
    title: "ExtensioMob",
    client: "Confidential",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-ExtensioMob.webp",
    liveUrl: "https://extensiomob.ro/",
    year: "2025",
    shortDescription: "Magazin online - mobilă transformabilă, Web design, Web Development, SEO",
    order: 62,
  },
  {
    id: "s63",
    title: "Sotherm România",
    client: "Sotherm SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-Sotherm.webp",
    liveUrl: "https://sotherm.ro/",
    year: "2025",
    shortDescription: "Magazin Online - Companie italiană de produse cosmetice, Web design, Web development, SEO",
    order: 10,
  },
  {
    id: "s64",
    title: "PV System",
    client: "PV System SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-PVsystems.webp",
    liveUrl: "https://pvsystem.ro/",
    year: "2025",
    shortDescription: "Magazin online și calculator sisteme panouri fotovoltaice complete, sistem prețuri în funcție de rolul utilizatorului, Web design, Web development, Mentenanță, domeniu, SEO",
    order: 2,
  },
  {
    id: "s65",
    title: "Ceramiqa",
    client: "Ceramiqa SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-Ceramiqa.webp",
    liveUrl: "https://ceramiqa.ro/",
    year: "2025",
    shortDescription: "Magazin online produse sanitare și decor, Web design, Web development, Design grafic, Mentenanță, SEO, Logo & Branding design",
    order: 65,
  },
  {
    id: "s66",
    title: "Pet Zaniverse",
    client: "Zaniverse SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-zaniverse.webp",
    liveUrl: "http://petzaniverse.ro/",
    year: "2026",
    shortDescription: "Magazin online pet shop, Web design, Web development, Design grafic, Mentenanță, SEO, Logo & Branding design",
    order: 12,
  },
  {
    id: "s67",
    title: "Sotherm Italia",
    client: "Sotherm Italia SRL",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-sotherm-italia.webp",
    liveUrl: "https://sotherm.it/",
    year: "2025",
    shortDescription: "Platformă online pentru organizarea evenimentelor, Web design, Web development, React-Next.js, Mentenanță, Găzduire, Logo & Branding design, SEO",
    order: 11,
  },
  {
    id: "s68",
    title: "The Permanent",
    client: "Beauty That Lasts LTD",
    category: "ecommerce",
    categoryLabel: "Magazin online",
    image: "/projects/magazin-online-the-permanent.webp",
    liveUrl: "https://the-permanent.com/",
    year: "2025",
    shortDescription: "Magazin online pentru produse cosmetice, sistem de fidelizare clienți, Web design, Web development, Mentenanță, SEO",
    order: 8,
  },
  // Platforme custom
  {
    id: "s70",
    title: "Document Rapid",
    client: "Team-Cad Vest SRL",
    category: "custom",
    categoryLabel: "Platformă custom",
    image: "/projects/platforma-online-extrasCF-documentrapid.webp",
    liveUrl: "https://documentrapid.ro/",
    year: "2025",
    shortDescription: "Platformă online pentru achizitionarea extraselor CF ANCPI, Web design, Web development, Mentenanță, Găzduire, SEO",
    order: 17,
  },
  {
    id: "s71",
    title: "Displayer",
    client: "Displayer SRL",
    category: "ecommerce",
    categoryLabel: "Catalog online",
    image: "/projects/catalog-online-magazin-displayer.webp",
    liveUrl: "https://www.displayer.ro/",
    year: "2025",
    shortDescription: "Website de prezentare standuri expo, Web design, Web development, Mentenanță, SEO",
    order: 18,
  },
]

export const categoryFilters = [
  { value: "all", label: "Toate proiectele" },
  { value: "website", label: "Website-uri" },
  { value: "ecommerce", label: "Magazine online" },
  { value: "custom", label: "Platforme custom" },
]
